# This rule is not used by the project agent-op itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to mcpgateway.bedrock.aws resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: agent-op
    app.kubernetes.io/managed-by: kustomize
  name: mcpserver-viewer-role
rules:
- apiGroups:
  - mcpgateway.bedrock.aws
  resources:
  - mcpservers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - mcpgateway.bedrock.aws
  resources:
  - mcpservers/status
  verbs:
  - get
