apiVersion: mcpgateway.bedrock.aws/v1alpha1
kind: MCPServer
metadata:
  name: mcp-jicomusic
  namespace: default
spec:
  endpoint: https://mcp-test.jicomusic.com
  authType: OAuth2
  oauthProviderArn: arn:aws:bedrock-agentcore:us-west-2:820537372947:token-vault/default/oauth2credentialprovider/test-mcp-oauth-https
  oauthScopes:
    - read
    - write
  capabilities:
    - tools
  description: MCP server with valid TLS certificate via ACM
