apiVersion: mcpgateway.bedrock.aws/v1alpha1
kind: MCPServer
metadata:
  labels:
    app.kubernetes.io/name: agent-op
    app.kubernetes.io/managed-by: kustomize
  name: mcpserver-sample
spec:
  # TODO(user): Add fields here
